# Generated by Django 5.0.3 on 2024-03-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='autor',
            new_name='author',
        ),
    ]
